# Generated by Django 5.0.6 on 2024-05-25 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_portfolio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
